import { type Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'
import colors from 'tailwindcss/colors'

export default {
  darkMode: 'media',
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './es/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    colors: {
      inherit: colors.inherit,
      transparent: colors.transparent,
      current: colors.current,
      white: colors.white,
      black: colors.black,
      gray: colors.gray,
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-primary) / <alpha-value>) /* #1677ff */',
          hover: 'var(--color-primary-hover) /* #4096ff */',
          active: 'var(--color-primary-active) /* #0958d9 */',
        },
        success: {
          DEFAULT: 'rgb(var(--color-success) / <alpha-value>) /* #52c41a */',
          hover: 'var(--color-success-hover) /* #95de64 */',
          active: 'var(--color-success-active) /* #389e0d */',
        },
        warning: {
          DEFAULT: 'rgb(var(--color-warning) / <alpha-value>) /* #faad14 */',
          hover: 'var(--color-warning-hover) /* #ffd666 */',
          active: 'var(--color-warning-active) /* #d48806 */',
        },
        error: {
          DEFAULT: 'rgb(var(--color-error) / <alpha-value>) /* #ff4d4f */',
          hover: 'var(--color-error-hover) /* #ff7875 */',
          active: 'var(--color-error-active) /* #d9363e */',
        },
        info: {
          DEFAULT: 'rgb(var(--color-info) / <alpha-value>) /* #1677ff */',
          hover: 'var(--color-info-hover) /* #69b1ff */',
          active: 'var(--color-info-active) /* #0958d9 */',
        },
        blue: {
          '50': 'rgb(var(--blue-1) / <alpha-value>) /* #e6f4ff */',
          '100': 'rgb(var(--blue-2) / <alpha-value>) /* #bae0ff */',
          '200': 'rgb(var(--blue-3) / <alpha-value>) /* #91caff */',
          '300': 'rgb(var(--blue-4) / <alpha-value>) /* #69b1ff */',
          '400': 'rgb(var(--blue-5) / <alpha-value>) /* #4096ff */',
          '500': 'rgb(var(--blue-6) / <alpha-value>) /* #1677ff */',
          '600': 'rgb(var(--blue-7) / <alpha-value>) /* #0958d9 */',
          '700': 'rgb(var(--blue-8) / <alpha-value>) /* #003eb3 */',
          '800': 'rgb(var(--blue-9) / <alpha-value>) /* #002c8c */',
          '900': 'rgb(var(--blue-10) / <alpha-value>) /* #001d66 */',
          DEFAULT: 'rgb(var(--blue) / <alpha-value>) /* #1677ff */',
        },
        purple: {
          '50': 'rgb(var(--purple-1) / <alpha-value>) /* #f9f0ff */',
          '100': 'rgb(var(--purple-2) / <alpha-value>) /* #efdbff */',
          '200': 'rgb(var(--purple-3) / <alpha-value>) /* #d3adf7 */',
          '300': 'rgb(var(--purple-4) / <alpha-value>) /* #b37feb */',
          '400': 'rgb(var(--purple-5) / <alpha-value>) /* #9254de */',
          '500': 'rgb(var(--purple-6) / <alpha-value>) /* #722ed1 */',
          '600': 'rgb(var(--purple-7) / <alpha-value>) /* #531dab */',
          '700': 'rgb(var(--purple-8) / <alpha-value>) /* #391085 */',
          '800': 'rgb(var(--purple-9) / <alpha-value>) /* #22075e */',
          '900': 'rgb(var(--purple-10) / <alpha-value>) /* #120338 */',
          DEFAULT: 'rgb(var(--purple) / <alpha-value>) /* #722ED1 */',
        },
        cyan: {
          '50': 'rgb(var(--cyan-1) / <alpha-value>) /* #e6fffb */',
          '100': 'rgb(var(--cyan-2) / <alpha-value>) /* #b5f5ec */',
          '200': 'rgb(var(--cyan-3) / <alpha-value>) /* #87e8de */',
          '300': 'rgb(var(--cyan-4) / <alpha-value>) /* #5cdbd3 */',
          '400': 'rgb(var(--cyan-5) / <alpha-value>) /* #36cfc9 */',
          '500': 'rgb(var(--cyan-6) / <alpha-value>) /* #13c2c2 */',
          '600': 'rgb(var(--cyan-7) / <alpha-value>) /* #08979c */',
          '700': 'rgb(var(--cyan-8) / <alpha-value>) /* #006d75 */',
          '800': 'rgb(var(--cyan-9) / <alpha-value>) /* #00474f */',
          '900': 'rgb(var(--cyan-10) / <alpha-value>) /* #002329 */',
          DEFAULT: 'rgb(var(--cyan) / <alpha-value>) /* #13C2C2 */',
        },
        green: {
          '50': 'rgb(var(--green-1) / <alpha-value>) /* #f6ffed */',
          '100': 'rgb(var(--green-2) / <alpha-value>) /* #d9f7be */',
          '200': 'rgb(var(--green-3) / <alpha-value>) /* #b7eb8f */',
          '300': 'rgb(var(--green-4) / <alpha-value>) /* #95de64 */',
          '400': 'rgb(var(--green-5) / <alpha-value>) /* #73d13d */',
          '500': 'rgb(var(--green-6) / <alpha-value>) /* #52c41a */',
          '600': 'rgb(var(--green-7) / <alpha-value>) /* #389e0d */',
          '700': 'rgb(var(--green-8) / <alpha-value>) /* #237804 */',
          '800': 'rgb(var(--green-9) / <alpha-value>) /* #135200 */',
          '900': 'rgb(var(--green-10) / <alpha-value>) /* #092b00 */',
          DEFAULT: 'rgb(var(--green) / <alpha-value>) /* #52C41A */',
        },
        magenta: {
          '50': 'rgb(var(--magenta-1) / <alpha-value>) /* #fff0f6 */',
          '100': 'rgb(var(--magenta-2) / <alpha-value>) /* #ffd6e7 */',
          '200': 'rgb(var(--magenta-3) / <alpha-value>) /* #ffadd2 */',
          '300': 'rgb(var(--magenta-4) / <alpha-value>) /* #ff85c0 */',
          '400': 'rgb(var(--magenta-5) / <alpha-value>) /* #f759ab */',
          '500': 'rgb(var(--magenta-6) / <alpha-value>) /* #eb2f96 */',
          '600': 'rgb(var(--magenta-7) / <alpha-value>) /* #c41d7f */',
          '700': 'rgb(var(--magenta-8) / <alpha-value>) /* #9e1068 */',
          '800': 'rgb(var(--magenta-9) / <alpha-value>) /* #780650 */',
          '900': 'rgb(var(--magenta-10) / <alpha-value>) /* #520339 */',
          DEFAULT: 'rgb(var(--magenta) / <alpha-value>) /* #EB2F96 */',
        },
        pink: {
          '50': 'rgb(var(--pink-1) / <alpha-value>) /* #fff0f6 */',
          '100': 'rgb(var(--pink-2) / <alpha-value>) /* #ffd6e7 */',
          '200': 'rgb(var(--pink-3) / <alpha-value>) /* #ffadd2 */',
          '300': 'rgb(var(--pink-4) / <alpha-value>) /* #ff85c0 */',
          '400': 'rgb(var(--pink-5) / <alpha-value>) /* #f759ab */',
          '500': 'rgb(var(--pink-6) / <alpha-value>) /* #eb2f96 */',
          '600': 'rgb(var(--pink-7) / <alpha-value>) /* #c41d7f */',
          '700': 'rgb(var(--pink-8) / <alpha-value>) /* #9e1068 */',
          '800': 'rgb(var(--pink-9) / <alpha-value>) /* #780650 */',
          '900': 'rgb(var(--pink-10) / <alpha-value>) /* #520339 */',
          DEFAULT: 'rgb(var(--pink) / <alpha-value>) /* #eb2f96 */',
        },
        red: {
          '50': 'rgb(var(--red-1) / <alpha-value>) /* #fff1f0 */',
          '100': 'rgb(var(--red-2) / <alpha-value>) /* #ffccc7 */',
          '200': 'rgb(var(--red-3) / <alpha-value>) /* #ffa39e */',
          '300': 'rgb(var(--red-4) / <alpha-value>) /* #ff7875 */',
          '400': 'rgb(var(--red-5) / <alpha-value>) /* #ff4d4f */',
          '500': 'rgb(var(--red-6) / <alpha-value>) /* #f5222d */',
          '600': 'rgb(var(--red-7) / <alpha-value>) /* #cf1322 */',
          '700': 'rgb(var(--red-8) / <alpha-value>) /* #a8071a */',
          '800': 'rgb(var(--red-9) / <alpha-value>) /* #820014 */',
          '900': 'rgb(var(--red-10) / <alpha-value>) /* #5c0011 */',
          DEFAULT: 'rgb(var(--red) / <alpha-value>) /* #F5222D */',
        },
        orange: {
          '50': 'rgb(var(--orange-1) / <alpha-value>) /* #fff7e6 */',
          '100': 'rgb(var(--orange-2) / <alpha-value>) /* #ffe7ba */',
          '200': 'rgb(var(--orange-3) / <alpha-value>) /* #ffd591 */',
          '300': 'rgb(var(--orange-4) / <alpha-value>) /* #ffc069 */',
          '400': 'rgb(var(--orange-5) / <alpha-value>) /* #ffa940 */',
          '500': 'rgb(var(--orange-6) / <alpha-value>) /* #fa8c16 */',
          '600': 'rgb(var(--orange-7) / <alpha-value>) /* #d46b08 */',
          '700': 'rgb(var(--orange-8) / <alpha-value>) /* #ad4e00 */',
          '800': 'rgb(var(--orange-9) / <alpha-value>) /* #873800 */',
          '900': 'rgb(var(--orange-10) / <alpha-value>) /* #612500 */',
          DEFAULT: 'rgb(var(--orange) / <alpha-value>) /* #FA8C16 */',
        },
        yellow: {
          '50': 'rgb(var(--yellow-1) / <alpha-value>) /* #feffe6 */',
          '100': 'rgb(var(--yellow-2) / <alpha-value>) /* #ffffb8 */',
          '200': 'rgb(var(--yellow-3) / <alpha-value>) /* #fffb8f */',
          '300': 'rgb(var(--yellow-4) / <alpha-value>) /* #fff566 */',
          '400': 'rgb(var(--yellow-5) / <alpha-value>) /* #ffec3d */',
          '500': 'rgb(var(--yellow-6) / <alpha-value>) /* #fadb14 */',
          '600': 'rgb(var(--yellow-7) / <alpha-value>) /* #d4b106 */',
          '700': 'rgb(var(--yellow-8) / <alpha-value>) /* #ad8b00 */',
          '800': 'rgb(var(--yellow-9) / <alpha-value>) /* #876800 */',
          '900': 'rgb(var(--yellow-10) / <alpha-value>) /* #614700 */',
          DEFAULT: 'rgb(var(--yellow) / <alpha-value>) /* #FADB14 */',
        },
        volcano: {
          '50': 'rgb(var(--volcano-1) / <alpha-value>) /* #fff2e8 */',
          '100': 'rgb(var(--volcano-2) / <alpha-value>) /* #ffd8bf */',
          '200': 'rgb(var(--volcano-3) / <alpha-value>) /* #ffbb96 */',
          '300': 'rgb(var(--volcano-4) / <alpha-value>) /* #ff9c6e */',
          '400': 'rgb(var(--volcano-5) / <alpha-value>) /* #ff7a45 */',
          '500': 'rgb(var(--volcano-6) / <alpha-value>) /* #fa541c */',
          '600': 'rgb(var(--volcano-7) / <alpha-value>) /* #d4380d */',
          '700': 'rgb(var(--volcano-8) / <alpha-value>) /* #ad2102 */',
          '800': 'rgb(var(--volcano-9) / <alpha-value>) /* #871400 */',
          '900': 'rgb(var(--volcano-10) / <alpha-value>) /* #610b00 */',
          DEFAULT: 'rgb(var(--volcano) / <alpha-value>) /* #FA541C */',
        },
        geekblue: {
          '50': 'rgb(var(--geekblue-1) / <alpha-value>) /* #f0f5ff */',
          '100': 'rgb(var(--geekblue-2) / <alpha-value>) /* #d6e4ff */',
          '200': 'rgb(var(--geekblue-3) / <alpha-value>) /* #adc6ff */',
          '300': 'rgb(var(--geekblue-4) / <alpha-value>) /* #85a5ff */',
          '400': 'rgb(var(--geekblue-5) / <alpha-value>) /* #597ef7 */',
          '500': 'rgb(var(--geekblue-6) / <alpha-value>) /* #2f54eb */',
          '600': 'rgb(var(--geekblue-7) / <alpha-value>) /* #1d39c4 */',
          '700': 'rgb(var(--geekblue-8) / <alpha-value>) /* #10239e */',
          '800': 'rgb(var(--geekblue-9) / <alpha-value>) /* #061178 */',
          '900': 'rgb(var(--geekblue-10) / <alpha-value>) /* #030852 */',
          DEFAULT: 'rgb(var(--geekblue) / <alpha-value>) /* #2F54EB */',
        },
        gold: {
          '50': 'rgb(var(--gold-1) / <alpha-value>) /* #fffbe6 */',
          '100': 'rgb(var(--gold-2) / <alpha-value>) /* #fff1b8 */',
          '200': 'rgb(var(--gold-3) / <alpha-value>) /* #ffe58f */',
          '300': 'rgb(var(--gold-4) / <alpha-value>) /* #ffd666 */',
          '400': 'rgb(var(--gold-5) / <alpha-value>) /* #ffc53d */',
          '500': 'rgb(var(--gold-6) / <alpha-value>) /* #faad14 */',
          '600': 'rgb(var(--gold-7) / <alpha-value>) /* #d48806 */',
          '700': 'rgb(var(--gold-8) / <alpha-value>) /* #ad6800 */',
          '800': 'rgb(var(--gold-9) / <alpha-value>) /* #874d00 */',
          '900': 'rgb(var(--gold-10) / <alpha-value>) /* #613400 */',
          DEFAULT: 'rgb(var(--gold) / <alpha-value>) /* #FAAD14 */',
        },
        lime: {
          '50': 'rgb(var(--lime-1) / <alpha-value>) /* #fcffe6 */',
          '100': 'rgb(var(--lime-2) / <alpha-value>) /* #f4ffb8 */',
          '200': 'rgb(var(--lime-3) / <alpha-value>) /* #eaff8f */',
          '300': 'rgb(var(--lime-4) / <alpha-value>) /* #d3f261 */',
          '400': 'rgb(var(--lime-5) / <alpha-value>) /* #bae637 */',
          '500': 'rgb(var(--lime-6) / <alpha-value>) /* #a0d911 */',
          '600': 'rgb(var(--lime-7) / <alpha-value>) /* #7cb305 */',
          '700': 'rgb(var(--lime-8) / <alpha-value>) /* #5b8c00 */',
          '800': 'rgb(var(--lime-9) / <alpha-value>) /* #3f6600 */',
          '900': 'rgb(var(--lime-10) / <alpha-value>) /* #254000 */',
          DEFAULT: 'rgb(var(--lime) / <alpha-value>) /* #A0D911 */',
        },
      },
      textColor: {
        DEFAULT: 'var(--color-text) /* #1E1E1E */',
        secondary: 'var(--color-text-secondary) /* #595959 */',
        tertiary: 'var(--color-text-tertiary) /* #8C8C8C */',
        quaternary: 'var(--color-text-quaternary) /* #BFBFBF */',
      },
      borderColor: {
        base: 'var(--color-border) /* #d9d9d9 */',
        secondary: 'var(--color-border-secondary) /* #f0f0f0 */',
      },
      backgroundColor: {
        container: 'var(--color-bg-container) /* #ffffff */',
        elevated: 'var(--color-bg-elevated) /* #ffffff */',
        layout: 'var(--color-bg-layout) /* #f5f5f5 */',
        spotlight: 'var(--color-bg-spotlight) /* rgba(0, 0, 0, 0.85) */',
        mask: 'var(--color-bg-mask) /* rgba(0, 0, 0, 0.45) */',
        fill: {
          DEFAULT: 'var(--color-fill) /* rgba(0, 0, 0, 0.15) */',
          secondary: 'var(--color-fill-secondary) /* rgba(0, 0, 0, 0.06) */',
          tertiary: 'var(--color-fill-tertiary) /* rgba(0, 0, 0, 0.04) */',
          quaternary: 'var(--color-fill-quaternary) /* rgba(0, 0, 0, 0.02) */',
        },
      },
      lineHeight: {
        DEFAULT: 'var(--line-height) /* 1.5714285714285714 */',
        sm: 'var(--line-height-sm) /* 1.6666666666666667 */',
        lg: 'var(--line-height-lg) /* 1.5 */',
        heading1: 'var(--line-height-heading1) /* 1.2105263157894737 */',
        heading2: 'var(--line-height-heading2) /* 1.2666666666666666 */',
        heading3: 'var(--line-height-heading3) /* 1.3333333333333333 */',
        heading4: 'var(--line-height-heading4) /* 1.4 */',
        heading5: 'var(--line-height-heading5) /* 1.5 */',
      },
      transitionTimingFunction: {
        'out-circ':
          'var(--motion-ease-out-circ) /* cubic-bezier(0.08, 0.82, 0.17, 1) */',
        'in-out-circ':
          'var(--motion-ease-in-out-circ) /* cubic-bezier(0.78, 0.14, 0.15, 0.86) */',
        out: 'var(--motion-ease-out) /* cubic-bezier(0.215, 0.61, 0.355, 1) */',
        'in-out':
          'var(--motion-ease-in-out) /* cubic-bezier(0.645, 0.045, 0.355, 1) */',
        'out-back':
          'var(--motion-ease-out-back) /* cubic-bezier(0.12, 0.4, 0.29, 1.46) */',
        'in-back':
          'var(--motion-ease-in-back) /* cubic-bezier(0.71, -0.46, 0.88, 0.6) */',
        'in-quint':
          'var(--motion-ease-in-quint) /* cubic-bezier(0.755, 0.05, 0.855, 0.06) */',
        'out-quint':
          'var(--motion-ease-out-quint) /* cubic-bezier(0.23, 1, 0.32, 1) */',
      },
      transitionDuration: {
        fast: 'var(--motion-duration-fast) /* 0.1s */',
        mid: 'var(--motion-duration-mid) /* 0.2s */',
        slow: 'var(--motion-duration-slow) /* 0.3s */',
      },
      fontSize: {
        sm: [
          'var(--font-size-sm) /* 12px */',
          'var(--line-height-sm) /* 1.6666666666666667 */',
        ],
        md: [
          'var(--font-size) /* 14px */',
          'var(--line-height) /* 1.5714285714285714 */',
        ],
        lg: [
          'var(--font-size-lg) /* 16px */',
          'var(--line-height-lg) /* 1.5 */',
        ],
        xl: [
          'var(--font-size-xl) /* 20px */',
          'var(--line-height-lg) /* 1.5 */',
        ],
        h1: [
          'var(--font-size-heading1) /* 38px */',
          {
            lineHeight: 'var(--line-height-heading1) /* 1.2105263157894737 */',
            fontWeight: '600',
          },
        ],
        h2: [
          'var(--font-size-heading2) /* 30px */',
          {
            lineHeight: 'var(--line-height-heading2) /* 1.2666666666666666 */',
            fontWeight: '600',
          },
        ],
        h3: [
          'var(--font-size-heading3) /* 24px */',
          {
            lineHeight: 'var(--line-height-heading3) /* 1.3333333333333333 */',
            fontWeight: '600',
          },
        ],
        h4: [
          'var(--font-size-heading4) /* 20px */',
          {
            lineHeight: 'var(--line-height-heading4) /* 1.4 */',
            fontWeight: '600',
          },
        ],
        h5: [
          'var(--font-size-heading5) /* 16px */',
          {
            lineHeight: 'var(--line-height-heading5) /* 1.5 */',
            fontWeight: '600',
          },
        ],
      },
      borderRadius: {
        DEFAULT: 'var(--border-radius) /* 6px */',
        xs: 'var(--border-radius-sm) /* 4px */',
        sm: 'var(--border-radius-sm) /* 4px */',
        lg: 'var(--border-radius-lg) /* 8px */',
        outer: 'var(--border-radius-outer) /* 4px */',
      },
      fontFamily: {
        system:
          "var(--font-family) /* -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial,\n'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',\n'Noto Color Emoji' */",
      },
    },
  },
  plugins: [
    plugin(({ addVariant }) => {
      ;['weapp', 'alipay', 'tt'].forEach((platform) => {
        addVariant(platform, '&')
      })
    }),
  ],
} as Config
